// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1yL_z4KxpkaFAF5f5-Zu33r-S1z3Hn6c',
    appId: '1:205766427957:web:a41d79e449ffd9b938f87c',
    messagingSenderId: '205766427957',
    projectId: 'flutter-project-f1271',
    authDomain: 'flutter-project-f1271.firebaseapp.com',
    storageBucket: 'flutter-project-f1271.appspot.com',
    measurementId: 'G-7CKBLP6B6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuU4o_CRXqQeKOjjDj0ENPFJwT9tdDWus',
    appId: '1:205766427957:android:a49b32af868051ba38f87c',
    messagingSenderId: '205766427957',
    projectId: 'flutter-project-f1271',
    storageBucket: 'flutter-project-f1271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Bl1ui2AmR-NeJ5rDgHP5pwPN8o8baoQ',
    appId: '1:205766427957:ios:ec7e9a5663e9133238f87c',
    messagingSenderId: '205766427957',
    projectId: 'flutter-project-f1271',
    storageBucket: 'flutter-project-f1271.appspot.com',
    androidClientId: '205766427957-6jura9thfufoap80mdvqa5rgcn80b198.apps.googleusercontent.com',
    iosClientId: '205766427957-8hf6u8e3rlg9cs80seufasqfhdkvq5rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Bl1ui2AmR-NeJ5rDgHP5pwPN8o8baoQ',
    appId: '1:205766427957:ios:da20cf94e9f134dc38f87c',
    messagingSenderId: '205766427957',
    projectId: 'flutter-project-f1271',
    storageBucket: 'flutter-project-f1271.appspot.com',
    androidClientId: '205766427957-6jura9thfufoap80mdvqa5rgcn80b198.apps.googleusercontent.com',
    iosClientId: '205766427957-jv66fbt866cbc3k5k2qoapnisrc6lkkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
